services:
  db:
    image: imresamu/postgis:16-3.5-alpine
    environment:
      POSTGRES_DB: vendocasa
      POSTGRES_USER: vendocasa
      POSTGRES_PASSWORD: vendocasa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
