services:
  db:
    image: postgis/postgis:16-3.4
    platform: linux/arm64
    environment:
      POSTGRES_DB: vendocasa
      POSTGRES_USER: vendocasa
      POSTGRES_PASSWORD: vendocasa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
